# -*- coding: utf-8 -*-
"""addition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZhR454I3JNIEgbU6jctdL9Bf_OyJcsD
"""

a=5
b=5
print(a+b)